# Generated by Django 4.2.3 on 2023-07-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatebusinessman",
            name="arrears_over_provider",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="privatebusinessman",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.storage"
            ),
        ),
        migrations.AlterField(
            model_name="retail",
            name="arrears_over_provider",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="retail",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.storage"
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="arrears_over_provider",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
