# Generated by Django 4.2.3 on 2023-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_privatebusinessman_arrears_over_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="arrears_over_provider",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
